### ISSUE TITLE
Allow to sort according to different criteria

### ISSUE THREAD

**Issue by xplosionmind** [awesome-selfhosted/awesome-selfhosted-html#1]
It would be nice to implement custom sorting capabilities. In particular, it would be nice to add the following criteria:

- stars
- clicks
- popularity

**Comment by xplosionmind** [comment]
I see that this issue already exists in the data repo. My bad, I did not check…

Sorry

**Comment by nodiscc** [comment]
-> https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues/77
